/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package temp_gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void OneIsNotEven() {
        assertFalse(App.isEven(1));
    }
    @Test public void ThreeIsNotEven() {
        assertFalse(App.isEven(3));
    }
    @Test public void twoIsNotOdd() {
        assertFalse(App.isOdd(2));
    }
    @Test public void sixIsDivBySix() {
        assertTrue(App.isDivBySix(6));
    }
}
