package temp_gradle;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void tenRootFive() {
        double toTest = Helper.root(10, 5);
        double actual = Math.pow(10, 1.0/5);
        boolean condition = toTest == actual;
        assertTrue(condition);
    }

    @Test
    public void fourRootTwo() {
        double toTest = Helper.root(4, 2);
        double actual = Math.sqrt(4);
        boolean condition = toTest == actual;
        assertTrue(condition);
    }

    @Test
    public void gRatioTest() {
        double epsilon = Math.pow(10, -15);
        double toTest = Library.gRatio();
        double actual = 1.618033988749894;
        boolean condition = Math.abs(toTest - actual) <= epsilon;
        assertTrue(condition);
    }

    @Test
    public void fib0Test() {
        assertTrue(Helper.fib(0) == 1);
    }
    @Test
    public void fib1Test() {
        assertTrue(Helper.fib(1) == 1);
    }

    @Test
    public void fib2Test() {
        assertTrue(Helper.fib(2) == 2);
    }

    @Test
    public void fib5Test() {
        assertTrue(Helper.fib(5) == 8);
    }

    @Test
    public void root10Test() {
        double epsilon = Math.pow(10, 15);
        double x = 100;
        double toTest = Library.x_Root10(x);
        double actual = Math.pow(x, 1.0/10);
        boolean condition = Math.abs(toTest - actual) <= epsilon;
        assertTrue(condition);
    }

    @Test
    public void simpTest() {
        double epsilon = Math.pow(10, -2);
        double toTest = Library.simpOfX_Root10(2, 100, 1000001);
        double actual = 142.132;
        boolean condition = Math.abs(toTest - actual) <= epsilon;
        assertTrue(condition);
    }
}