/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package temp_gradle;

public class App {
    public String getGreeting() {
        return null;
    }
    public static boolean isEven(int n) {
        return n%2 == 0 ;
    }
    public static boolean isOdd(int n) {
        return n%2 == 1;
    }

    public static boolean isDivByThree(int n) {
        return n%3 == 0;
    }

    public static boolean isDivBySix(int n) {
        return isEven(n) && isDivByThree(n);
    }

    public static void main(String[] args) {
    }
}
